---
postfix_instance:
  # The keys are the group names associated with a Postfix role, and the
  # values are the name and group (optional) of the instance dedicated
  # to that role.
  IMAP:    { name: mda                }
  MX:      { name: mx,     group: mta }
  MTA-out: { name: mta-out,group: mta }
  MSA:     { name: msa                }
  webmail: { name: webmail            }

MTA_out: { IPv4: outgoing.fripost.org, port: 2525 }
LDA:     { IPv4: lda.fripost.org,      port: 2526 }

LDAP_provider: host1.libvirt.guilhem.org
NTP_master: host1.libvirt.guilhem.org
IMAP: host1.libvirt.guilhem.org
