---
- name: Restart stunnel@ldap
  service: name=stunnel4@ldap state=restarted

- name: Restart php7.3-fpm
  service: name=php7.3-fpm state=restarted

- name: Restart Nginx
  service: name=nginx state=restarted
