- name: Install Postfix
  apt: pkg={{ item }}
  with_items:
    - postfix
    - postfix-pcre

- name: Configure Postfix
  template: src=etc/postfix/main.cf.j2
            dest=/etc/postfix-{{ postfix_instance[inst].name }}/main.cf
            owner=root group=root
            mode=0644
  notify:
    - Reload Postfix

- name: Copy the Regex to anonymize senders
  # no need to reload upon change, as cleanup(8) is short-running
  copy: src=etc/postfix/anonymize_sender.pcre
        dest=/etc/postfix-{{ postfix_instance[inst].name }}/anonymize_sender.pcre
        owner=root group=root
        mode=0644

- meta: flush_handlers

- name: Start Postfix
  service: name=postfix state=started
