- name: Install MariaDB
  apt: pkg={{ packages }}
  vars:
    packages:
    - mariadb-common
    - mariadb-server
    - python-mysqldb
    # for the 'mysql_' munin plugin
    - libcache-cache-perl

- name: Copy MySQL/MariaDB configuration
  copy: src=etc/mysql/mariadb.conf.d/99-user.cnf
        dest=/etc/mysql/mariadb.conf.d/99-user.cnf
        owner=root group=root
        mode=0644
  register: r
  notify:
    - Restart MariaDB

# We need to restart now and load the relevant authplugin before we
# connect to the database.
- meta: flush_handlers

# XXX Dirty fix for #742046
- name: Force root to use UNIX permissions
  mysql_user2: name=root password="" auth_plugin=unix_socket soname=auth_socket.so
               state=present

- name: Disallow anonymous and TCP/IP root login
  mysql_user2: name={{ item.name|default('') }} host={{ item.host }}
               state=absent
  with_items:
    - {             host: '{{ inventory_hostname_short }}' }
    - {             host: 'localhost' }
    - {             host: '127.0.0.1'}
    - {             host: '::1'}
    - { name: root, host: '{{ inventory_hostname_short }}' }
    - { name: root, host: '127.0.0.1'}
    - { name: root, host: '::1'}

- name: Start MariaDB
  service: name=mariadb state=started


- name: Install 'mysql_' Munin wildcard plugin
  file: src=/usr/share/munin/plugins/mysql_
        dest=/etc/munin/plugins/mysql_{{ item }}
        owner=root group=root
        state=link force=yes
  with_items:
    # sudo /usr/share/munin/plugins/mysql_ suggest
    - bin_relay_log
    - commands
    - connections
    - files_tables
    - innodb_bpool
    - innodb_bpool_act
    - innodb_io
    - innodb_log
    - innodb_rows
    - innodb_semaphores
    - innodb_tnx
    - myisam_indexes
    - qcache
    - qcache_mem
    - select_types
    - slow
    - sorts
    - table_locks
    - tmp_tables
  tags:
    - munin
    - munin-node
  notify:
    - Restart munin-node
