---
- name: Configure the Bacula Director
  hosts: bacula_dir
  tags:
    - bacula
    - bacula-dir
  roles:
      - bacula-dir

- name: Configure the Bacula Storage Daemon
  hosts: bacula_sd
  tags:
    - bacula
    - bacula-sd
  roles:
      - bacula-sd
