---
- name: Configure the IMAP server
  hosts: IMAP
  roles:
    - { role: IMAP, inst: IMAP }
  tags:
    - imap
    - dovecot

- name: Configure IMAP proxies
  hosts: webmail:!IMAP
  roles:
    - { role: IMAP-proxy, imapsvr: "{{ hostvars[groups.IMAP[0]] }}" }
  tags:
    - imap
    - dovecot
