---
- import_tasks: imap.yml
  tags:
    - imap
    - dovecot
- import_tasks: mda.yml
  tags:
    - mda
    - mail
    - postfix
## TODO spam filter
#- import_tasks: spam.yml
#  tags:
#    - spam
#    - amavis
#    - spamassassin
