- name: Install Postfix
  apt: pkg={{ item }}
  with_items:
    - postfix
    - postfix-ldap

- name: Configure Postfix
  template: src=etc/postfix/main.cf.j2
            dest=/etc/postfix-{{ postfix_instance[inst].name }}/main.cf
            owner=root group=root
            mode=0644
  notify:
    - Reload Postfix

- name: Copy the transport and recipient canonical maps
  copy: src=etc/postfix/{{ item }}
        dest=/etc/postfix-{{ postfix_instance[inst].name }}/{{ item }}
        owner=root group=root
        mode=0644
  with_items:
    # no need to reload upon change, as cleanup(8) is short-running
    - recipient_canonical.pcre
    - transport

- name: Copy the Postfix relay clientcerts map
  template: src=etc/postfix/relay_clientcerts.j2
            dest=/etc/postfix-{{ postfix_instance[inst].name }}/relay_clientcerts
            owner=root group=root
            mode=0644
  tags:
    - tls_policy

- name: Compile the Postfix relay clientcerts map
  postmap: cmd=postmap src=/etc/postfix-{{ postfix_instance[inst].name }}/relay_clientcerts db=cdb
           owner=root group=root
           mode=0644
  tags:
    - tls_policy

- name: Compile the Postfix transport maps
  # trivial-rewrite(8) is a long-running process, so it's safer to reload
  postmap: cmd=postmap src=/etc/postfix-{{ postfix_instance[inst].name }}/transport db=cdb
           owner=root group=root
           mode=0644
  notify:
    - Reload Postfix

- meta: flush_handlers

- name: Start Postfix
  service: name=postfix state=started
