- name: Install Postfix & Postgrey
  apt: pkg={{ item }}
  with_items:
    - postfix
    - postfix-pcre
    - postfix-ldap
    - postfix-cdb
    - postgrey
    - libnet-ldap-perl
    - libauthen-sasl-perl

- name: Configure Postgrey
  lineinfile: dest=/etc/default/postgrey
              regexp='^POSTGREY_OPTS='
              line='POSTGREY_OPTS="--privacy --unix=/var/spool/postfix-{{ postfix_instance[inst].name }}/private/postgrey"'
              owner=root group=root
              mode=0644
  register: r
  notify:
    - Restart Postgrey

- name: Start Postgrey
  service: name=postgrey state=started
  when: not r.changed

- meta: flush_handlers

- name: Configure Postfix
  template: src=etc/postfix/main.cf.j2
            dest=/etc/postfix-{{ postfix_instance[inst].name }}/main.cf
            owner=root group=root
            mode=0644
  notify:
    - Reload Postfix

- name: Create directory /etc/postfix-.../virtual
  file: path=/etc/postfix-{{ postfix_instance[inst].name }}/virtual
        state=directory
        owner=root group=root
        mode=0755

- name: Copy lookup tables
  template: src=etc/postfix/virtual/{{ item }}.j2
            dest=/etc/postfix-{{ postfix_instance[inst].name }}/virtual/{{ item }}
            owner=root group=root
            mode=0644
  with_items:
    - mailbox_domains.cf
    # no need to reload upon change, as cleanup(8) is short-running
    - reserved_alias.pcre
    - alias.cf
    - mailbox.cf
    - list.cf
    - alias_domains.cf
    - catchall.cf
    - transport

- name: Compile the Reserved Transport Maps
  postmap: instance={{ postfix_instance[inst].name }}
           src=/etc/postfix-{{ postfix_instance[inst].name }}/virtual/transport db=cdb
           owner=root group=root
           mode=0644

- name: Copy reserved-alias.pl
  copy: src=usr/local/sbin/reserved-alias.pl
        dest=/usr/local/sbin/reserved-alias.pl
        owner=root group=root
        mode=0755

- meta: flush_handlers

- name: Start Postfix
  service: name=postfix state=started
