- name: Install Postfix
  apt: pkg={{ item }}
  with_items:
    - postfix
    - postfix-pcre
    - postfix-ldap
    - postfix-cdb
    # The following is for reserved-alias.pl
    - libnet-ldap-perl
    - libauthen-sasl-perl

- name: Configure Postfix
  template: src=etc/postfix/main.cf.j2
            dest=/etc/postfix-{{ postfix_instance[inst].name }}/main.cf
            owner=root group=root
            mode=0644
  notify:
    - Reload Postfix

- name: Create directory /etc/postfix-.../virtual
  file: path=/etc/postfix-{{ postfix_instance[inst].name }}/virtual
        state=directory
        owner=root group=root
        mode=0755

# trivial-rewrite(8) runs in a chroot.  We create an empty
# /usr/lib/sasl2 to avoid "No such file or directory" warnings.
# Cf. also #738989.
- name: Create directory /usr/lib/sasl2
  file: path=/var/spool/postfix-{{ postfix_instance[inst].name }}/{{ item }}
        state=directory
        owner=root group=root
        mode=0755
  with_items:
    - /usr/lib/sasl2
    - /usr/lib/{{ ansible_architecture }}-linux-gnu/sasl2
  notify:
    - Reload Postfix

- name: Copy lookup tables (1)
  copy: src=etc/postfix/virtual/{{ item }}
        dest=/etc/postfix-{{ postfix_instance[inst].name }}/virtual/{{ item }}
        owner=root group=root
        mode=0644
  with_items:
    - domains.cf
    # no need to reload upon change, as cleanup(8) is short-running
    - reserved_alias.pcre
    - alias.cf
    - mailbox.cf
    - list.cf
    - alias_domains.cf
    - catchall.cf

- name: Copy lookup tables (2)
  template: src=etc/postfix/virtual/transport.j2
            dest=/etc/postfix-{{ postfix_instance[inst].name }}/virtual/transport
            owner=root group=root
            mode=0644

- name: Compile the Postfix transport maps
  # trivial-rewrite(8) is a long-running process, so it's safer to reload
  postmap: instance={{ postfix_instance[inst].name }}
           src=/etc/postfix-{{ postfix_instance[inst].name }}/virtual/transport db=cdb
           owner=root group=root
           mode=0644
  notify:
    - Reload Postfix

- name: Copy reserved-alias.pl
  copy: src=usr/local/bin/reserved-alias.pl
        dest=/usr/local/bin/reserved-alias.pl
        owner=root group=root
        mode=0755

- meta: flush_handlers

- name: Start Postfix
  service: name=postfix state=started
