#!/bin/sh

# Munin plugin for monitoring Dovecot IMAP connections and unique users.
# Copyright © 2015 Guilhem Moulin <guilhem@fripost.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

PATH=/usr/bin:/bin:/usr/sbin:/sbin
set -u

case "${1:-}" in
    config) cat <<- EOF
		graph_title Dovecot concurrent IMAP usage
		graph_args --base 1000 -l 0
		graph_scale no
		graph_category dovecot
		connections.label connections
		connections.min 0
		users.label unique users
		users.min 0
	EOF
    exit 0
    ;;
esac

tmpfile="$(mktemp --tmpdir)"
trap 'rm -f "$tmpfile"' EXIT

doveadm -f flow who -1 | sed -nr 's/^username=(\S+)\s+proto=imap\s.*/\1/p' >"$tmpfile"

echo connections.value $(wc -l <"$tmpfile")
echo users.value       $(sort -u "$tmpfile" | wc -l)
