- name: Install Postfix
  apt: pkg={{ packages }}
  vars:
    packages:
    - postfix
    - postfix-ldap

- name: Configure Postfix
  template: src=etc/postfix/{{ item }}.j2
            dest=/etc/postfix-{{ postfix_instance[inst].name }}/{{ item }}
            owner=root group=root
            mode=0644
  with_items:
    - main.cf
    - master.cf
  notify:
    - Reload Postfix

- name: Copy the transport maps
  copy: src=etc/postfix/transport
        dest=/etc/postfix-{{ postfix_instance[inst].name }}/transport
        owner=root group=root
        mode=0644
  # no need to reload upon change, as cleanup(8) is short-running

- name: Compile the Postfix transport maps
  # trivial-rewrite(8) is a long-running process, so it's safer to reload
  postmap: cmd=postmap src=/etc/postfix-{{ postfix_instance[inst].name }}/transport db=lmdb
           owner=root group=root
           mode=0644
  notify:
    - Reload Postfix

- meta: flush_handlers

- name: Start Postfix
  service: name=postfix state=started

- name: Copy the 'sympa-queue' wrapper
  copy: src=usr/local/bin/sympa-queue
        dest=/usr/local/bin/sympa-queue
        owner=root group=staff
        mode=0755


- name: Install 'postfix_mailqueue_' Munin wildcard plugin
  file: src=/usr/local/share/munin/plugins/postfix_mailqueue_
        dest=/etc/munin/plugins/postfix_mailqueue_postfix-{{ postfix_instance[inst].name }}
        owner=root group=root
        state=link force=yes
  tags:
    - munin
    - munin-node
  notify:
    - Restart munin-node

- name: Install 'postfix_stats_' Munin wildcard plugin
  file: src=/usr/local/share/munin/plugins/postfix_stats_
        dest=/etc/munin/plugins/postfix_stats_{{ item }}_postfix-{{ postfix_instance[inst].name }}
        owner=root group=root
        state=link force=yes
  with_items:
    - smtpd
    - qmgr
    - smtp
    - pipe
  tags:
    - munin
    - munin-node
  notify:
    - Restart munin-node
