- apt: pkg={{ packages }} install_recommends=no
  vars:
    packages:
    - mariadb-server
    - sympa
    - libnet-dns-perl
    - libnet-dns-sec-perl
    - libmail-dkim-perl
    - libcrypt-smime-perl
    - libcrypt-openssl-x509-perl

- name: Make the 'sympa' MySQL user use unix_socket
  mysql_user2: name=sympa password= auth_plugin=unix_socket
               state=present

- name: Configure Sympa
  copy: src=etc/sympa/{{ item }}
        dest=/etc/sympa/{{ item }}
        owner=root group=sympa
        mode=0644
  with_items:
    - sympa/sympa.conf
    - topics.conf
  register: r1
  notify:
    - Restart Sympa

- name: Create Virtual hosts for Sympa (1)
  file: path=/etc/sympa/{{ item }}
        state=directory
        owner=sympa group=sympa
        mode=0755
  with_items:
    - lists.fripost.org
  register: r2
  notify:
    - Restart Sympa

- name: Create Virtual hosts for Sympa (2)
  file: path=/var/lib/sympa/list_data/{{ item }}
        state=directory
        owner=sympa group=sympa
        mode=0770
  with_items:
    - lists.fripost.org
  register: r3
  notify:
    - Restart Sympa

- name: Install robot.conf
  template: src=etc/sympa/robot.conf.j2
            dest=/etc/sympa/{{ item }}/robot.conf
            owner=sympa group=sympa
            mode=0640
  with_items:
    - lists.fripost.org
  register: r4
  notify:
    - Restart Sympa

- name: Enable Sympa
  service: name=sympa enabled=yes

- name: Start Sympa
  service: name=sympa state=started
  when: not (r1.changed or r2.changed or r3.changed or r4.changed)

- meta: flush_handlers

- name: Copy wwsympa.{service,socket}
  copy: src=etc/systemd/system/{{ item }}
        dest=/etc/systemd/system/{{ item }}
        owner=root group=root
        mode=0644
  notify:
    - systemctl daemon-reload
    - Restart wwsympa
  with_items:
    - wwsympa.service
    - wwsympa.socket

- meta: flush_handlers

- name: Enable WWSympa
  service: name=wwsympa enabled=yes

- name: Start WWSympa
  service: name=wwsympa state=started
