- name: Install Nginx
  apt: pkg=nginx

- name: Limit Nginx logging
  lineinfile: "dest=/etc/logrotate.d/nginx create=yes
               regexp='^\\s*rotate\\s'
               line='\trotate 1'"
  tags:
    - logrotate

- name: Copy fastcgi parameters, acme-challenge and SSL configuration snippets
  copy: src=etc/nginx/snippets/{{ item }}
        dest=/etc/nginx/snippets/{{ item }}
        owner=root group=root
        mode=0644
  register: r1
  with_items:
    - fastcgi.conf
    - fastcgi-php.conf
    - fastcgi-php-ssl.conf
    - ssl.conf
    - headers.conf
    - acme-challenge.conf
  notify:
    - Restart Nginx

- name: Copy /etc/nginx/sites-available/default
  copy: src=etc/nginx/sites-available/default
        dest=/etc/nginx/sites-available/default
        owner=root group=root
        mode=0644
  register: r2
  notify:
    - Restart Nginx

- name: Create /etc/nginx/sites-enabled/default
  file: src=../sites-available/default
        dest=/etc/nginx/sites-enabled/default
        owner=root group=root
        state=link force=yes
  register: r3
  notify:
    - Restart Nginx

- name: Add .asc to text/plain MIME types
  lineinfile: dest=/etc/nginx/mime.types
              regexp='^(\s*text/plain\s+)'
              backrefs=yes
              line='\1txt asc;'
  register: r4
  notify:
    - Restart Nginx

- name: Start Nginx
  service: name=nginx state=started
  when: not (r1.changed or r2.changed or r3.changed or r4.changed)

- meta: flush_handlers
