- name: Install Nginx
  apt: pkg=nginx

- name: Limit Nginx logging
  lineinfile: "dest=/etc/logrotate.d/nginx create=yes
               regexp='^\\s*rotate\\s'
               line='\trotate 1'"
  tags:
    - logrotate

- name: Delete /etc/nginx/sites-{available,enabled}/default
  file: path=/etc/nginx/sites-{{ item }}/default state=absent
  with_items:
    - enabled
    - available

- name: Create directory /etc/nginx/{fastcgi,ssl}
  file: path=/etc/nginx/{{ item }}
        state=directory
        owner=root group=root
        mode=0755
  with_items:
    - fastcgi
    - ssl

- name: Copy fastcgi parameters
  copy: src=etc/nginx/fastcgi/{{ item }}
        dest=/etc/nginx/fastcgi/{{ item }}
        owner=root group=root
        mode=0644
  register: r1
  with_items:
    - params
    - php
    - php-ssl
  notify:
    - Restart Nginx

- name: Copy SSL configuration
  copy: src=etc/nginx/ssl/config
        dest=/etc/nginx/ssl/config
        owner=root group=root
        mode=0644
  register: r2
  notify:
    - Restart Nginx

- name: Add .asc to text/plain MIME types
  lineinfile: dest=/etc/nginx/mime.types
              regexp='^(\s*text/plain\s+)'
              backrefs=yes
              line='\1txt asc;'
  register: r3
  notify:
    - Restart Nginx

- name: Start Nginx
  service: name=nginx state=started
  when: not (r1.changed or r2.changed or r3.changed)

- meta: flush_handlers
