- name: Install Postfix
  apt: pkg=postfix

- name: Configure Postfix
  template: src=etc/postfix/main.cf.j2
            dest=/etc/postfix-{{ postfix_instance[inst].name }}/main.cf
            owner=root group=root
            mode=0644
  notify:
    - Reload Postfix

- name: Copy the Postfix relay clientcerts map
  template: src=etc/postfix/relay_clientcerts.j2
            dest=/etc/postfix-{{ postfix_instance[inst].name }}/relay_clientcerts
            owner=root group=root
            mode=0644
  tags:
    - tls_policy

- name: Compile the Postfix relay clientcerts map
  postmap: cmd=postmap src=/etc/postfix-{{ postfix_instance[inst].name }}/relay_clientcerts db=cdb
           owner=root group=root
           mode=0644
  tags:
    - tls_policy

- meta: flush_handlers

- name: Start Postfix
  service: name=postfix state=started


- name: Install 'postfix_mailqueue_' Munin wildcard plugin
  file: src=/usr/local/share/munin/plugins/postfix_mailqueue_
        dest=/etc/munin/plugins/postfix_mailqueue_postfix-{{ postfix_instance[inst].name }}
        owner=root group=root
        state=link force=yes
  tags:
    - munin
    - munin-node
  notify:
    - Restart munin-node

- name: Install 'postfix_stats_' Munin wildcard plugin
  file: src=/usr/local/share/munin/plugins/postfix_stats_
        dest=/etc/munin/plugins/postfix_stats_{{ item }}_postfix-{{ postfix_instance[inst].name }}
        owner=root group=root
        state=link force=yes
  with_items:
    - smtpd
    - qmgr
    - smtp
  tags:
    - munin
    - munin-node
  notify:
    - Restart munin-node
