- name: Install Postfix
  apt: pkg=postfix

- name: Configure Postfix
  template: src=etc/postfix/main.cf.j2
            dest=/etc/postfix-{{ postfix_instance[inst].name }}/main.cf
            owner=root group=root
            mode=0644
  notify:
    - Reload Postfix

- name: Build the Postfix relay clientcerts map
  sudo: False
  # smtpd_tls_fingerprint_digest MUST be sha256!
  local_action: shell openssl x509 -in certs/postfix/{{ item }}.pem -noout -fingerprint -sha256 | sed -nr 's/^.*=(.*)/\1 {{ item }}/p'
  with_items: groups.all | difference([inventory_hostname]) | sort
  register: relay_clientcerts
  changed_when: False
  tags:
    - tls_policy

- name: Copy the Postfix relay clientcerts map
  template: src=etc/postfix/relay_clientcerts.j2
            dest=/etc/postfix-{{ postfix_instance[inst].name }}/relay_clientcerts
            owner=root group=root
            mode=0644
  tags:
    - tls_policy

- name: Compile the Postfix relay clientcerts map
  postmap: cmd=postmap src=/etc/postfix-{{ postfix_instance[inst].name }}/relay_clientcerts db=cdb
           owner=root group=root
           mode=0644
  tags:
    - tls_policy

- meta: flush_handlers

- name: Start Postfix
  service: name=postfix state=started
