---
- name: systemctl daemon-reload
  command: /bin/systemctl daemon-reload

- name: Reload Postfix
  service: name=postfix state=reloaded

- name: Restart munin-node
  service: name=munin-node state=restarted
