- name: Install lacme
  apt: pkg={{ packages }} install_recommends=no
  vars:
    packages:
    - liblwp-protocol-https-perl
    - lacme

- name: Create a user 'lacme'
  user: name=lacme system=yes
        group=nogroup
        createhome=no
        home=/nonexistent
        shell=/usr/sbin/nologin
        password=!
        state=present

- name: Copy lacme/lacme-certs.conf
  copy: src=etc/lacme/lacme.conf
        dest=/etc/lacme/lacme.conf
        owner=root group=root
        mode=0644

- name: Copy lacme/lacme-certs.conf
  template: src=etc/lacme/lacme-certs.conf.j2
            dest=/etc/lacme/lacme-certs.conf
            owner=root group=root
            mode=0644
