- name: Install dependencies for lacme
  apt: pkg={{ item }}
  with_items:
    - libjson-perl
    - libjson-xs-perl
    - libconfig-tiny-perl
    - libwww-perl
    - liblwp-protocol-https-perl
    - libnet-ssleay-perl

- name: Copy lacme
  copy: src=deb/lacme_0.1-1_all.deb
        dest=/tmp
  notify: Install lacme

- meta: flush_handlers

- name: Create a user 'lacme'
  user: name=lacme system=yes
        group=nogroup
        createhome=no
        home=/nonexistent
        shell=/usr/sbin/nologin
        password=!
        state=present

- name: Copy lacme/lacme-certs.conf
  copy: src=etc/lacme/lacme.conf
        dest=/etc/lacme/lacme.conf
        owner=root group=root
        mode=0644

- name: Copy lacme/lacme-certs.conf
  template: src=etc/lacme/lacme-certs.conf.j2
            dest=/etc/lacme/lacme-certs.conf
            owner=root group=root
            mode=0644
