- name: Load and configure the syncprov overlay
  openldap: module=syncprov state=present
            suffix=o=mailHosting,dc=fripost,dc=org
            target=etc/ldap/syncprov.ldif
            local=file

# TODO: authz constraint
