- name: Load and configure the syncprov overlay
  openldap: module=syncprov
            suffix=dc=fripost,dc=org
            target=etc/ldap/syncprov.ldif
            local=file

- name: Enable the EXTERNAL SASL mechanism
  lineinfile: dest=/usr/lib/sasl2/slapd.conf
              regexp='^mech_list'':'
              line=mech_list':'' EXTERNAL'
              create=yes
              owner=root group=root
              mode=0644

# TODO: authz constraint
