# 'service: name=... state=started' tasks should NOT run if there is a
# corresponding state=restarted handler.  (Register the task notifying
# the handler, and add a conditional.)
---
- name: systemctl daemon-reload
  command: /bin/systemctl daemon-reload

- name: Refresh hostname
  service: name=hostname.sh state=restarted

- name: apt-get update
  apt: update_cache=yes

- name: Reload samhain
  service: name=samhain state=reloaded

- name: Update rkhunter's data file
  command: /usr/bin/rkhunter --propupd

- name: Restart fail2ban
  service: name=fail2ban state=restarted

- name: Reload networking
  # /etc/init.d/networking doesn't answer the status command; but since
  # it should be "up" whenever ansible has access to the machine, we use
  # pattern=init as a dummy assumption.
  service: name=networking pattern=init state=reloaded

- name: Restart rsyslog
  service: name=rsyslog state=restarted

- name: Restart ntp
  service: name=ntp state=restarted

- name: Restart Postfix
  service: name=postfix state=restarted

- name: Reload Postfix
  service: name=postfix state=reloaded

- name: Restart stunnel
  service: name=stunnel4 pattern=/usr/bin/stunnel4 state=restarted

- name: Restart bacula-fd
  service: name=bacula-fd state=restarted

- name: Update certificate
  command: update-ca-certificates

- name: Restart munin-node
  service: name=munin-node state=restarted

- name: Restart freshclam
  service: name=clamav-freshclam state=restarted

- name: Install LetsEncrypt's ACME client
  apt: deb=/tmp/letsencrypt-tiny_0.1-1_all.deb
