---
- name: Refresh hostname
  service: name=hostname.sh state=restarted

- name: apt-get update
  apt: update_cache=yes

- name: Unsafe firewall update
  fail: msg="The firewall has been updated, but not activated yet; an unsafe
    update may lock you and others out! Please log in to '{{ ansible_fqdn }}' and
    manually run 'sudo update-firewall.sh'."
