- name: Install Dovecot
  apt: pkg={{ item }} default_release={{ ansible_lsb.codename }}-backports
  with_items:
    - dovecot-core
    - dovecot-imapd

- name: Create a user 'imapproxy'
  user: name=imapproxy system=yes
        home=/home/imapproxy
        shell=/bin/false
        password=!
        state=present

- name: Create a home directory for user 'imapproxy'
  file: path=/home/imapproxy
        state=directory
        owner=imapproxy group=imapproxy
        mode=0700

- name: Configure Dovecot
  copy: src=etc/dovecot/conf.d/{{ item }}
        dest=/etc/dovecot/conf.d/{{ item }}
        owner=root group=root
        mode=0644
  register: r
  with_items:
    - 10-auth.conf
    - 10-logging.conf
    - 10-mail.conf
    - 10-master.conf
    - 15-mailboxes.conf
    - 20-imapc.conf
    - auth-imap.conf.ext
  notify:
    - Restart Dovecot

- name: Start Dovecot
  service: name=dovecot state=started
  when: not r.changed

- meta: flush_handlers
