- name: Install amavis and its decoders
  apt: pkg={{ item }}
  with_items:
    - amavisd-new
    - libnet-ldap-perl
    # Mail::DKIM
    - libmail-dkim-perl
    - gzip
    - bzip2
    - xz-utils
    - lzop
    - rpm2cpio
    - pax
    - binutils
    - p7zip-full
    - unrar-free
    - arj
    - nomarch
    - zoo
    - ripole
    - cabextract
    - unar
    - tnef
  notify:
    - Restart Amavis

- name: Add 'clamav' to the group 'amavis'
  user: name=clamav groups=amavis append=yes
  notify:
    - Restart ClamAV
    - Restart Amavis

- name: Add an 'amavis' alias
  lineinfile: dest=/etc/aliases create=yes
              regexp="^amavis{{':'}} "
              line="amavis{{':'}} root"

- name: Compile the static local Postfix database
  postmap: cmd=postalias src=/etc/aliases db=cdb
           owner=root group=root
           mode=0644

- name: Create directory /var/lib/dkim
  file: path=/var/lib/dkim
        state=directory
        owner=root group=root
        mode=0755
  when: "'out' in group_names"
  tags:
    - genkey

- name: Generate a private key for DKIM signing
  command: genkeypair.sh dkim --privkey=/var/lib/dkim/20140703.fripost.org.key -t rsa -b 1024
  register: dkim
  changed_when: dkim.rc == 0
  failed_when: dkim.rc > 1
  when: "'out' in group_names"
  notify:
    - Restart Amavis
    - Publish the public key to the DNS zone
  tags:
    - genkey

- name: Configure Amavis
  template: src=etc/amavis/conf.d/50-user.j2
            dest=/etc/amavis/conf.d/50-user
            owner=root group=root
            mode=0644
  register: r3
  notify:
    - Restart Amavis

- meta: flush_handlers

- name: Start Amavis
  service: name=amavis state=started


- name: Install 'amavis' Munin plugin
  file: src=/usr/share/munin/plugins/amavis
        dest=/etc/munin/plugins/amavis
        owner=root group=root
        state=link force=yes
  tags:
    - munin
    - munin-node
  notify:
    - Restart munin-node
