- name: Install amavis and its decoders
  apt: pkg={{ item }}
  with_items:
    - amavisd-new
    # Mail::DKIM
    - libmail-dkim-perl
    - gzip
    - bzip2
    - xz-utils
    - lzop
    - rpm2cpio
    - pax
    - binutils
    - p7zip-full
    - unrar-free
    - arj
    - nomarch
    - zoo
    - ripole
    - cabextract
    - unar
    - tnef
  notify:
    - Restart Amavis

- name: Add 'clamav' to the group 'amavis'
  user: name=clamav groups=amavis append=yes
  register: r1
  notify:
    - Restart ClamAV
    - Restart Amavis

- name: Create directory /var/lib/dkim
  file: path=/var/lib/dkim
        state=directory
        owner=root group=root
        mode=0755

- name: Generate a private key for DKIM signing
  command: genkeypair.sh dkim --privkey=/var/lib/dkim/outgoing.fripost.org.key --dns=outgoing -t rsa -b 2048
  register: dkim
  changed_when: dkim.rc == 0
  failed_when: dkim.rc > 1
  notify:
    - Restart Amavis
    - Publish the public key to the DNS zone
  tags:
    - genkey

- name: Configure Amavis
  template: src=etc/amavis/conf.d/50-user.j2
            dest=/etc/amavis/conf.d/50-user
            owner=root group=root
            mode=0644
  register: r3
  notify:
    - Restart Amavis

- meta: flush_handlers

- name: Start Amavis
  service: name=amavis state=started
