---
- name: systemctl daemon-reload
  command: /bin/systemctl daemon-reload

- name: Restart stunnel
  service: name=stunnel4 pattern=/usr/bin/stunnel4 state=restarted

- name: Restart bacula-director
  service: name=bacula-director state=restarted
