- name: Install Postfix
  apt: pkg={{ item }}
  with_items:
    - postfix
    - postfix-pcre

- name: Configure Postfix
  template: src=etc/postfix/main.cf.j2
            dest=/etc/postfix-{{ postfix_instance[inst].name }}/main.cf
            owner=root group=root
            mode=0644
  register: r
  notify:
    - Restart Postfix

- name: Start Postfix
  service: name=postfix state=started
  when: not r.changed

- meta: flush_handlers
