- name: Install Postfix
  apt: pkg=postfix

- name: Configure Postfix
  template: src=etc/postfix/main.cf.j2
            dest=/etc/postfix-{{ postfix_instance[inst].name }}/main.cf
            owner=root group=root
            mode=0644
  notify:
    - Reload Postfix

- meta: flush_handlers

- name: Start Postfix
  service: name=postfix state=started
