---
- name: systemctl daemon-reload
  command: /bin/systemctl daemon-reload

- name: Restart stunnel@bacula-sd
  service: name=stunnel4@bacula-sd state=restarted

- name: Restart bacula-sd
  service: name=bacula-sd state=restarted
