- name: Install various APT tools
  apt: pkg={{ packages }}
  vars:
    packages:
    - apt
    - apt-listchanges
    - apt-show-versions
    - debian-archive-keyring
    - debian-goodies
    - needrestart
    - unattended-upgrades
    - debfoster
    - deborphan
    - debsums

- name: Configure APT (1)
  template: src=etc/apt/{{ item }}.j2
            dest=/etc/apt/{{ item }}
            owner=root group=root
            mode=0644
  with_items:
    - sources.list
    - preferences
  notify:
    - apt-get update

- name: Configure APT (2)
  copy: src=etc/apt/{{ item }}
        dest=/etc/apt/{{ item }}
        owner=root group=root
        mode=0644
  with_items:
    - listchanges.conf
    - apt.conf.d/10periodic
    - apt.conf.d/50unattended-upgrades

- name: Start cron
  service: name=cron state=started
  tags:
    - cron

# We should run 'apt-get update' before proceeding to any other task.
- meta: flush_handlers
