- name: Install ClamAV
  apt: pkg={{ item }}
  with_items:
    - clamav
    - clamav-daemon
    - clamav-freshclam

- name: Configure FreshClam
  lineinfile: "dest=/etc/clamav/freshclam.conf
              line='DatabaseMirror {{ item }}'"
  with_items:
    - db.local.clamav.net
    - database.clamav.net
    - db.other.clamav.net
  notify:
    - Restart freshclam

- name: Start ClamAV
  service: name={{ item }} state=started
  with_items:
    - clamav-daemon
    - clamav-freshclam
