- name: Install ClamAV
  apt: pkg={{ item }}
  with_items:
    - clamav
    - clamav-daemon
    - clamav-freshclam

- name: Configure FreshClam
  template: src=etc/clamav/freshclam.conf.j2
            dest=/etc/clamav/freshclam.conf
            owner=root group=root
            mode=0644
  tags: freshclam
  notify:
    - Restart freshclam

- name: Start ClamAV
  service: name={{ item }} state=started
  with_items:
    - clamav-daemon
    - clamav-freshclam
