- name: Set hostname
  template: src=etc/hostname.j2
            dest=/etc/hostname
            owner=root group=root
            mode=0644
  tags: hostname
  notify:
    - Refresh hostname

- name: Set mailname
  template: src=etc/mailname.j2
            dest=/etc/mailname
            owner=root group=root
            mode=0644
  tags: mailname

- name: Fix /etc/hosts (1)
  lineinfile: dest=/etc/hosts create=yes
              regexp="^127\.0\.0\.1\s+"
              line="127.0.0.1    localhost"
  tags: hosts

- name: Fix /etc/hosts (2)
  lineinfile: dest=/etc/hosts create=yes
              regexp="^127\.0\.1\.1\s+"
              line="127.0.1.1    {{ inventory_hostname }} {{ inventory_hostname_short }}"
  tags: hosts
