- name: Install Postfix
  apt: pkg={{ item }}
  with_items:
    # That one is nicer than GNU mailutils' mailx(1)
    - heirloom-mailx
    - postfix
    - postfix-cdb

- name: Create Postfix instances
  postmulti: instance={{ postfix_instance[item].name }}
             group={{ postfix_instance[item].group | default('') }}
  register: r1
  with_items: "{{ postfix_instance.keys() | intersect(group_names) | list }}"
  notify:
    - Restart Postfix

- name: Link the dynamic maps of each children to the master's
  # main.cf and master.cf are specialized to each dedicated role, though
  file: src=../postfix/dynamicmaps.cf
        dest=/etc/postfix-{{ postfix_instance[item].name }}/dynamicmaps.cf
        owner=root group=root
        state=link force=yes
  register: r2
  with_items: "{{ postfix_instance.keys() | intersect(group_names) | list }}"
  notify:
    - Restart Postfix

- name: Configure Postfix
  template: src=etc/postfix/{{ item }}.j2
            dest=/etc/postfix/{{ item }}
            owner=root group=root
            mode=0644
  with_items:
    - main.cf
    - master.cf
  notify:
    - Reload Postfix

- name: Add some common aliases
  lineinfile: dest=/etc/aliases create=yes
              regexp='^{{ item.src }}{{':'}} '
              line='{{ item.src }}{{':'}} {{ item.dst }}'
  with_items:
    - { src: mailer-daemon, dst: 'postmaster'       }
    - { src: postmaster,    dst: 'root'             }
    - { src: nobody,        dst: 'root'             }
    - { src: root,          dst: 'root@fripost.org' }

- name: Compile the static local Postfix database
  postmap: cmd=postalias src=/etc/aliases db=cdb
           owner=root group=root
           mode=0644

# We're using CDB
- name: Delete /etc/aliases.db
  file: path=/etc/aliases.db state=absent

- name: Start Postfix
  service: name=postfix state=started
  when: not (r1.changed or r2.changed)

- meta: flush_handlers
