- name: Install Postfix
  apt: pkg={{ item }}
  with_items:
    # That one is nicer than GNU mailutils' mailx(1)
    - heirloom-mailx
    - postfix
    - postfix-cdb
    - postfix-pcre

- name: Create Postfix instances
  postmulti: instance={{ postfix_instance[item].name }}
             group={{ postfix_instance[item].group | default('') }}
  register: r1
  with_items: postfix_instance.keys() | intersect(group_names) | list
  notify:
    - Restart Postfix

- name: Link the dynamic maps & master.cf of each children to the master's
  # main.cf is specialized to each dedicated role, though
  file: src=../postfix/{{ item.1 }}
        dest=/etc/postfix-{{ postfix_instance[item.0].name }}/{{ item.1 }}
        owner=root group=root
        state=link force=yes
  register: r2
  with_nested:
    - postfix_instance.keys() | intersect(group_names) | list
    - [ 'dynamicmaps.cf', 'master.cf' ]
  notify:
    - Restart Postfix

- name: Configure Postfix (1)
  copy: src=etc/postfix/{{ item }}
        dest=/etc/postfix/{{ item }}
        owner=root group=root
        mode=0644
  with_items:
    - master.cf
    - generic.pcre
  notify:
    - Reload Postfix

- name: Configure Postfix (2)
  template: src=etc/postfix/main.cf.j2
            dest=/etc/postfix/main.cf
            owner=root group=root
            mode=0644
  register: r3
  notify:
    - Restart Postfix

- name: Update the static local Postfix database
  postmap: cmd=postalias src=/etc/aliases db=cdb
           owner=root group=root
           mode=0644

# We're using CDB
- name: Delete /etc/aliases.db
  file: path=/etc/aliases.db state=absent

- name: Start Postfix
  service: name=postfix state=started
  when: not (r1.changed or r2.changed or r3.changed)

- meta: flush_handlers
