---
- include: sysctl.yml   tags=sysctl
- include: hosts.yml
- include: apt.yml      tags=apt
- include: firewall.yml tags=firewall,iptables
- include: samhain.yml  tags=samhain
- include: rkhunter.yml tags=rkhunter
- include: clamav.yml   tags=clamav
- include: fail2ban.yml tags=fail2ban
- include: smart.yml    tags=smartmontools,smart
- include: haveged.yml  tags=haveged,entropy
- name: Copy genkeypair.sh
  copy: src=usr/local/bin/genkeypair.sh
        dest=/usr/local/bin/genkeypair.sh
        owner=root group=root
        mode=0755
  tags:
    - genkey
- include: logging.yml  tags=logging
- include: ntp.yml      tags=ntp
- include: mail.yml     tags=mail,postfix

- name: Install common packages
  apt: pkg={{ item }}
  with_items:
    - ca-certificates
    - daemontools
    - etckeeper
    - ethtool
    - git
    - harden-clients
    - harden-servers
    - htop
    - molly-guard
    - rsync
    - screen
    - telnet-ssl
