---
- include: sysctl.yml   tags=sysctl
- include: hosts.yml
- include: apt.yml      tags=apt
- include: firewall.yml tags=firewall,iptables
- include: samhain.yml  tags=samhain
- include: rkhunter.yml tags=rkhunter
- include: fail2ban.yml tags=fail2ban
- include: ipsec.yml    tags=strongswan,ipsec
- include: logging.yml  tags=logging
- include: mail.yml     tags=mail,postfix
- include: sql.yml      tags=mysql,sql
  # XXX: the conditional here is a bit dirty, because it clutters the
  # output with 'skipping' notices.
  when: "'MDA'     in group_names or
         'webmail' in group_names or
         'backup'  in group_names"
