---
- include: sysctl.yml   tags=sysctl
- include: hosts.yml
- include: apt.yml      tags=apt
- include: firewall.yml tags=firewall,iptables
- include: samhain.yml  tags=samhain
- include: rkhunter.yml tags=rkhunter
- include: fail2ban.yml tags=fail2ban
