- name: Install ntp
  apt: pkg=ntp

- name: Configure ntp
  template: src=etc/ntp.conf.j2
            dest=/etc/ntp.conf
            owner=root group=root
            mode=0644
  register: r
  notify:
    - Restart ntp

- name: Start ntp
  service: name=ntp state=started
  when: not r.changed

- meta: flush_handlers
