- name: Install smartmontools
  # apt-listbugs complains due to #706909.
  apt: pkg=smartmontools

- name: Auto-enable smartmontools
  lineinfile: dest=/etc/default/smartmontools
              regexp='^(\s*#)?\s*start_smartd='
              line='start_smartd=yes'
              owner=root group=root
              mode=0644

- name: Start smartd
  service: name=smartmontools state=started
  # smartd can be heavy on VMs, don't bother starting it up if it's down
  when: not (ansible_processor[0] | search("^QEMU Virtual CPU .*"))
