- name: Install smartmontools
  apt: pkg=smartmontools

- name: Auto-enable smartmontools
  lineinfile: dest=/etc/default/smartmontools
              regexp='^(\s*#)?\s*start_smartd='
              line='start_smartd=yes'
              owner=root group=root
              mode=0644

- name: Start smartd
  service: name=smartmontools state=started
