- name: Install stunnel4
  apt: pkg=stunnel4

- name: Set 'ENABLED=0' in /etc/default/stunnel4
  lineinfile: dest=/etc/default/stunnel4
              regexp='^(\s*#)?\s*ENABLED='
              line='ENABLED=0'
              owner=root group=root
              mode=0644

- name: Copy stunnel4 service file
  copy: src=lib/systemd/system/{{ item }}
        dest=/lib/systemd/system/{{ item }}
        owner=root group=root
        mode=0644
  notify:
    - systemctl daemon-reload
  with_items:
    - stunnel4.service
    - stunnel4@.service
