- name: Install stunnel4
  apt: pkg=stunnel4

- name: Copy stunnel4 service files
  copy: src=etc/systemd/system/{{ item }}
        dest=/etc/systemd/system/{{ item }}
        owner=root group=root
        mode=0644
  notify:
    - systemctl daemon-reload
  with_items:
    - stunnel4.service
    - stunnel4@.service

- name: Disable stunnel4 service
  service: name=stunnel4.service enabled=false
