- name: Install dependencies for letsencrypt-tiny
  apt: pkg={{ item }}
  with_items:
    - libjson-perl
    - libjson-xs-perl
    - libconfig-tiny-perl
    - libwww-perl
    - liblwp-protocol-https-perl
    - libnet-ssleay-perl

- name: Copy LetsEncrypt's ACME client
  copy: src=deb/letsencrypt-tiny_0.1-1_all.deb
        dest=/tmp
  notify: Install LetsEncrypt's ACME client

- meta: flush_handlers

- name: Create a user 'letsencrypt'
  user: name=letsencrypt system=yes
        group=nogroup
        createhome=no
        home=/nonexistent
        shell=/usr/sbin/nologin
        password=!
        state=present

- name: Copy letsencrypt-tiny/letsencrypt-certs.conf
  copy: src=etc/letsencrypt-tiny/letsencrypt.conf
        dest=/etc/letsencrypt-tiny/letsencrypt.conf
        owner=root group=root
        mode=0644

- name: Copy letsencrypt-tiny/letsencrypt-certs.conf
  template: src=etc/letsencrypt-tiny/letsencrypt-certs.conf.j2
            dest=/etc/letsencrypt-tiny/letsencrypt-certs.conf
            owner=root group=root
            mode=0644
